[workspace]
members = [
    "demos/faucet",
    "demos/hubbub",
    "demos/powerwidget_demo",
    "subpax/hubbub_subhub",
    "subpax/powerwidget",
]
resolver = "2"

[workspace.package]
rust-version = "1.70.0"
version = "0.3.0"

[workspace.dependencies]
ambient_api = { git = "https://github.com/AmbientRun/Ambient.git", branch = "main" }