[package]
id = "ndwzyelnsxa6krn4akc5d6t4dky3gkxl"
name = "hubbub"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.1"

[dependencies]
subhub = { path = "../../subpax/hubbub_subhub"} # not being used at the moment
pixie = { path = "../../subpax/pixie" }
powerwidget = { path = "../../subpax/powerwidget" }
# jellybean = { deployment = "7Lab4cQjHhoXAE0P7jR8PO" } # let's do a simple platformer character

include_very_simple_jumper = { path = "../very_simple_jumper" } # spawn this on its own layer, let's just see how the messages interact

# [components]
# ui_anim_time = { type = "F32" }
# sent_time = { type = "F32" }
# sent_text = { type = "String" }

[components]

# used serverside
message_rate_counter = { type = "F32" }

# used clientside
cs_msgs_rcvd = { type = "U32" }
cs_msgs_rcvd_last_frame = { type = "U32" }

[messages.TextToClient.fields]
text = "String"