[package]
id = "ndwzyelnsxa6krn4akc5d6t4dky3gkxl"
name = "hubbub"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.1"

[dependencies]
subhub = { path = "../../subpax/hubbub_subhub"}
pixie = { path = "../../subpax/pixie" }
powerwidget = { path = "../../subpax/powerwidget" }

# [components]
# ui_anim_time = { type = "F32" }
# sent_time = { type = "F32" }
# sent_text = { type = "String" }