[package]
id = "v77zj56hzswnc24jadrvrhpnnlpbvvox"
name = "powerwidget_demo"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.1-nightly-2023-10-26"

[dependencies]
powerwidget = { path = "../../subpax/powerwidget" }